### ISSUE TITLE
performance

### ISSUE THREAD

**Issue by toufikbelouadah** [leaf2fire/userChrome#1]
since your approach uses userChrome.js to load *.us.css files under ./css/ this unfortunatly takes time so i will have to see the ugly fat firefox css untill the js loads and loads my us.css file to see my beautiful custum rice ><

**Comment by leaf2fire** [comment]
Thank you for your input! Immersion is definitely important. There are three things I can currently think of that might help.

1. A script to concatenate relevant css files while adding '! important' to all properties and put them in userChrome.css. This skips JS completely and should cover most of the elements though not the scrollbar unfortunately.
2. By pass the call to the FileIO directory iterator (this is very slow actually) and list relevant files directly in userChrome.js. We can make another script automatically add files to the list.
3. (Unix like shells only. Not sure how to do this in Windows.) Make elements like scrollbar initially invisible in GTK and set alias of Firefox to 'GTK_THEME=firefox_theme firefox' assuming you launch it from the terminal.

I'm traveling at the moment. Please wait patiently. :)

**Comment by toufikbelouadah** [comment]
thank you leaf2fire
well i did a dirty workaround 

i removed the 'css' parameter from userChrome.js, so the script will only look in chrome directory 
i moved the scrollbar.uc.js to parent directory ( chrome/ ) and removed css folder 

also i embeded my rice css in the userChrome.css below your code so that userchrome call xbl/js to load the scrollbar.uc.js and my load my rice css at the same time ^^ 

this solved my issue
